version: '3'

services:
  # payload:
  #   image: node:18-alpine
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #     - /home/node/app/.next
  #   working_dir: /home/node/app/
  #   command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ppidktimtengka
      POSTGRES_PASSWORD: R8vjMWv8N86X
      POSTGRES_DB: ppidktimtengka

volumes:
  data:
  node_modules:
